baseURL = '/'
languageCode = 'pt-BR'
title = 'Renesas Product Training'
theme = "etch"

[params]
  description = "Your site description"
  copyright = "Copyright © 2023 Renesas Electronics"
  dark = "auto"
  highlight = true
